Make the -k flag required
This will avoid getting the following error when ommiting it:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/brouberol/bin/.env/lib/python3.11/site-packages/kafkacfg/data/None.json'
```